In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.linear_model import Lasso,Ridge,ElasticNet
from sklearn.metrics import r2_score, mean_absolute_error,mean_squared_error,mean_absolute_percentage_error
from sklearn.metrics import accuracy_score

In [2]:
df=pd.read_csv(r"C:\Users\Dhruv\Downloads\insurance.csv")
df.head(5)

   age     sex     bmi  children smoker     region      charges
0   19  female  27.900         0    yes  southwest  16884.92400
1   18    male  33.770         1     no  southeast   1725.55230
2   28    male  33.000         3     no  southeast   4449.46200
3   33    male  22.705         0     no  northwest  21984.47061
4   32    male  28.880         0     no  northwest   3866.85520

In [3]:
df.isnull().sum()

age         0
sex         0
bmi         0
children    0
smoker      0
region      0
charges     0
dtype: int64

In [4]:
df['sex']=df['sex'].replace({'male':0,'female':1})
df['smoker']=df['smoker'].replace({'yes':0,'no':1})
df['region']=df['region'].replace({'northeast':0,'northwest':1,'southeast':2,'southwest':3})

C:\Users\Dhruv\AppData\Local\Temp\ipykernel_11796\626182626.py:1: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['sex']=df['sex'].replace({'male':0,'female':1})
C:\Users\Dhruv\AppData\Local\Temp\ipykernel_11796\626182626.py:2: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['smoker']=df['smoker'].replace({'yes':0,'no':1})
C:\Users\Dhruv\AppData\Local\Temp\ipykernel_11796\626182626.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df['region']=df['region'].replace({'northeast':0,'northwest':1,'southeast':2,'southwest':3})

In [5]:
df.head(5)

   age  sex     bmi  children  smoker  region      charges
0   19    1  27.900         0       0       3  16884.92400
1   18    0  33.770         1       1       2   1725.55230
2   28    0  33.000         3       1       2   4449.46200
3   33    0  22.705         0       1       1  21984.47061
4   32    0  28.880         0       1       1   3866.85520

In [6]:
df.columns

Index(['age', 'sex', 'bmi', 'children', 'smoker', 'region', 'charges'], dtype='object')

In [7]:
X=df[['age', 'sex', 'bmi', 'children', 'smoker', 'region']]
y=df[['charges']]

In [8]:
# Features Selection
X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y, 
                                                    test_size=0.3, 
                                                    random_state=42)

In [9]:
# Scale data
scaler=StandardScaler()
X_train_scale=scaler.fit_transform(X_train,y_train)
X_test_scale=scaler.transform(X_test)

In [10]:
# model selection
lin_model=LinearRegression()
lin_model.fit(X_train_scale,y_train)
pred=lin_model.predict(X_test_scale)
print("Linear prediction:",r2_score(y_test,pred))

Linear prediction: 0.7694415927057693

In [11]:
print("model slope :",lin_model.coef_[0])
print("model intercept :",lin_model.intercept_)

model slope : [ 3693.22419232   -54.80557279  2064.85587799   514.32785602
 -9592.79601818  -363.35933577]
model intercept : [13379.15730677]

In [12]:
# model lasso
ls=Lasso(alpha=100)
ls.fit(X_train_scale,y_train)
pred_ls=ls.predict(X_test_scale)

In [13]:
# model Ridge
ri=Ridge(alpha=1)
ri.fit(X_train_scale,y_train)
pred_ri=ri.predict(X_test_scale)

In [14]:
# model elastic net
el=ElasticNet(alpha=1,l1_ratio=0.5)
el.fit(X_train_scale,y_train)
pred_el=el.predict(X_test_scale)

In [15]:
# R2 scores
print("r2 score Linear Regression:",r2_score(y_test,pred))
print("r2 score Lasso:",r2_score(y_test,pred_ls))
print("r2 score Ridge:",r2_score(y_test,pred_ri))
print("r2 score ElasticNet:",r2_score(y_test,pred_el))

r2 score Linear Regression: 0.7694415927057693
r2 score Lasso: 0.7692740535486439
r2 score Ridge: 0.7694227240163629
r2 score ElasticNet: 0.6785056910732254

In [17]:
mean_absolute_error_print = mean_absolute_error(y_test,pred)
print("mean_absolute_error :",mean_absolute_error_print)

mean_absolute_error_print = mean_squared_error(y_test,pred)
print("mean_squared_error :",mean_absolute_error_print)

mean_root_mean_squared_error_print = mean_squared_error(y_test,pred)
print("mean_root_mean_squared_error :",mean_root_mean_squared_error_print)

mean_absolute_error : 4155.239843059382
mean_squared_error : 33805466.898688614
mean_root_mean_squared_error : 33805466.898688614

In [ ]:
new_data = pd.DataFrame(
    [[35,0,60.775,4,1,2]],
    columns=['age', 'sex', 'bmi', 'children', 'smoker', 'region']
)

new_data_scaled = scaler.transform(new_data)
prediction = lin_model.predict(new_data_scaled)

print("Prediction:",prediction)