In [7]:
import pandas as pd

In [1]:
pwd

'C:\\Users\\Dhruv\\machine Learning'

In [11]:
df=pd.read_csv(r"C:\Users\Dhruv\Downloads\customer_purchase_dataset.csv")
df

   CustomerID  Age  Salary  Experience       City  Purchased
0           1   22   25000           1  Ahmedabad          0
1           2   25   30000           2      Surat          0
2           3   30   45000           5     Rajkot          1
3           4   35   50000           8  Ahmedabad          1
4           5   40   70000          12      Surat          1
5           6   28   35000           4   Vadodara          0
6           7   50   90000          20  Ahmedabad          1
7           8   29   38000           5     Rajkot          0
8           9   45   85000          18      Surat          1
9          10   60  250000          35  Ahmedabad          1

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 6 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   CustomerID  10 non-null     int64
 1   Age         10 non-null     int64
 2   Salary      10 non-null     int64
 3   Experience  10 non-null     int64
 4   City        10 non-null     object
 5   Purchased   10 non-null     int64
dtypes: int64(5), object(1)
memory usage: 612.0+ bytes

In [15]:
df.describe()

       CustomerID       Age         Salary  Experience  Purchased
count    10.00000  10.00000      10.000000   10.000000  10.000000
mean      5.50000  36.40000   71800.000000   11.000000   0.600000
std       3.02765  12.17648   66576.272049   10.635371   0.516398
min       1.00000  22.00000   25000.000000    1.000000   0.000000
25%       3.25000  28.25000   35750.000000    4.250000   0.000000
50%       5.50000  32.50000   47500.000000    6.500000   1.000000
75%       7.75000  43.75000   81250.000000   16.500000   1.000000
max      10.00000  60.00000  250000.000000   35.000000   1.000000

In [31]:
from scipy.stats import zscore

df['z_score'] = zscore(df['Salary'])
outlier = df[df['Salary'].abs() > 1.5]
outlier

   CustomerID  Age  Salary  Experience       City  Purchased   z_score
0           1   22   25000           1  Ahmedabad          0 -0.740978
1           2   25   30000           2      Surat          0 -0.661813
2           3   30   45000           5     Rajkot          1 -0.424321
3           4   35   50000           8  Ahmedabad          1 -0.345156
4           5   40   70000          12      Surat          1 -0.028499
5           6   28   35000           4   Vadodara          0 -0.582649
6           7   50   90000          20  Ahmedabad          1  0.288158
7           8   29   38000           5     Rajkot          0 -0.535151
8           9   45   85000          18      Surat          1  0.208994
9          10   60  250000          35  Ahmedabad          1  2.821415